dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  #  - openzepplin-contracts/contracts/token/ERC721@5.0.1
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
      #     - "@openzeppelin=openzepplin-contracts/contracts/token/ERC721@5.0.1"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  Sepolia:
    vrf_coordinator: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    link_token: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    key_hash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    fee: 250000000000000000 #.25LINK
