dependencies:
  - aave/protocol-v2@1.0.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
reports:
  exclude_contracts:
    - LinkToken
    - VRFCoordinatorMock
    - ERC721
    - EnumerableMap
    - Address
    - EnumerableSet
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@aave=aave/protocol-v2@1.0.1"
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  default: mainnet-fork
  development:
    keyhash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    fee: 5000000000000000
  kovan:
    weth_token: "0x4d3875545893e21BaE6F1E0aB137CC2D9451BfCc"
    lending_pool_addresses_provider: "0x5E52dEc931FFb32f609681B8438A51c675cc232d"
  mainnet-fork:
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    lending_pool_addresses_provider: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
  sepolia:
    vrf_coordinator: "0x8103B0A8A00be2DDC778e6e7eaa21791Cd364625"
    link_token: "0x779877A7B0D9E8603169DdbD7836e478b4624789"
    keyhash: "0x474e34a077df58807dbe9c96d3c009b23b3c6d0cce433e59bbf5b34f823bc56c"
    fee: 5000000000000000 # 0.005
