dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"
dotenv: .env
networks:
  development:
    verify: False
  ganache:
    verify: False
  Sepolia:
    verify: True
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
    fau_token: "0x52b9BfCd50f246BbD7dE51d13A05cDfe0F833DC4"
    dai_usd_price_feed: "0x14866185B1962B63C3Ea9E03Bc1da838bab34C19"
    eth_usd_price_feed: "0x694AA1769357215DE4FAC081bf1f309aDC325306"
wallets:
  from_key: ${PRIVATE_KEY}
